### PR TITLE
Update to 2.2.0

### LINKED ISSUE #3: Not working after update to osx 11.5.1
Hello there,

After upgrade, the list of AWS accounts no longer appear, same behaviour as if the URL are wrong.

Regards
Kristoffer

### PR DESCRIPTION
**Pull request by parkeyparker**
Fixes #3 and #4. Removed supporters/golden key features from the original plugin as appeared that such things may not pass Apple's app review.

### CODE REVIEW

**Comment by ibehren1** [comment]
Is there a secret to make this build locally?  Sorry, not an Apple developer.  Just get errors that I have no signing cert even after adding apple ID to xCode.

**Comment by parkeyparker** [comment]
> Is there a secret to make this build locally? Sorry, not an Apple developer. Just get errors that I have no signing cert even after adding apple ID to xCode.

I'm no expert I'm afraid so can't help too much other than to suggest the things I've had to do to get it building myself... The main thing when it comes to signing errors I think is to choose the root level project in the sidebar and then choose each item under "Targets" and go to the "Signing & Capabilities" tab. There's a drop down for "Team" which will need changing to your developer account team instead of the original author's (I changed my local copy back to that before committing and raising this PR so that it won't cause conflicts).

It's been quite a while with no updates on this and in the UK at least I can't see this in the app store so I am considering publishing it myself if I don't hear anything from the original author - I'd give appropriate thanks to the original author of course as well as the actual plugin author too...

**Comment by ibehren1** [comment]
Thanks @parkeyparker!  With that, I was able to compile and it works!

**Comment by parkeyparker** [comment]
Closing this as taken a different approach (Safari Web Extension vs Safari App Extension) which allows for this to run on iOS as well as MacOS. Not currently publishing the Xcode project. Both MacOS and iOS extensions are currently in App Review.

**Comment by dbektas** [comment]
@parkeyparker Hey Aaaron, could you give an update as soon as this extension passes App Review? Really helpfull! Ty

**Comment by parkeyparker** [comment]
@dbektas will do, however currently in discussions with the creator of the extension itself as I need to get their permission before I can actually release it.

**Comment by parkeyparker** [comment]
@dbektas It's passed App Review and the original creator is happy with me release it so you can now find it here: https://apps.apple.com/gb/app/aws-extend-switch-roles/id1592710340 (available for MacOS _and_ iOS which is super handy when quickly trying to do something on an iPad for example)

**Pull request closed without merging**
